LOAD DATA LOCAL INFILE 'itemTable.dat' INTO TABLE Items 
FIELDS TERMINATED BY '|*|';-- OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'categoryTable.dat' INTO TABLE Category 
FIELDS TERMINATED BY '|*|';-- OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'userTable.dat' INTO TABLE Users 
FIELDS TERMINATED BY '|*|';-- OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'bidTable.dat' INTO TABLE Bids 
FIELDS TERMINATED BY '|*|';-- OPTIONALLY ENCLOSED BY '"';
